### ISSUE TITLE
Installation question

### ISSUE THREAD

**Issue by Heinlein83** [ali-vilab/AnyDoor#51]
1. Where to put the  [epoch=1-step=8687.ckpt](https://huggingface.co/spaces/xichenhku/AnyDoor/blob/main/epoch%3D1-step%3D8687.ckpt) checkpoint? 
2. Which dinov2 checkpoint to download and where  to put it?
3. revise /configs/anydoor.yaml for the path (line 83) <- what to revise?

**Comment by aadinash** [comment]
1. You can put it wherever. Just edit the path of "pretrained_model" in inference.yaml and demo.yaml to match where you put it. I.e., if you put it at the root, just use the value "epoch=1-step=8687.ckpt" for it
2. I got this link from the repo: https://dl.fbaipublicfiles.com/dinov2/dinov2_vitg14/dinov2_vitg14_pretrain.pth
3. Just as earlier, you download the dinov2 model, and put it somewhere in your folder. Then you should edit "path/dinov2..." to the actual path to where you chose to put it

**Comment by Heinlein83** [comment]
Actually anyone use anydoor for AMD gpu? Does it work or it only works for Nvidia gpu?

**Comment by Heinlein83** [comment]
I got this error. Anyone know what I did wrong?

Traceback (most recent call last):
  File "F:\AnyDoor-for-windows\run_gradio_demo.py", line 32, in <module>
    model = create_model(model_config ).cpu()
  File "F:\AnyDoor-for-windows\cldm\model.py", line 26, in create_model
    model = instantiate_from_config(config.model).cpu()
  File "F:\AnyDoor-for-windows\ldm\util.py", line 81, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "F:\AnyDoor-for-windows\cldm\cldm.py", line 310, in __init__
    super().__init__(*args, **kwargs)
  File "F:\AnyDoor-for-windows\ldm\models\diffusion\ddpm.py", line 565, in __init__
    self.instantiate_cond_stage(cond_stage_config)
  File "F:\AnyDoor-for-windows\ldm\models\diffusion\ddpm.py", line 632, in instantiate_cond_stage
    model = instantiate_from_config(config)
  File "F:\AnyDoor-for-windows\ldm\util.py", line 81, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "F:\AnyDoor-for-windows\ldm\modules\encoders\modules.py", line 287, in __init__
    dinov2.load_state_dict(state_dict, strict=False)
  File "F:\AnyDoor-for-windows\venv\lib\site-packages\torch\nn\modules\module.py", line 2152, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for DinoVisionTransformer:
        size mismatch for cls_token: copying a param with shape torch.Size([1, 1, 384]) from checkpoint, the shape in current model is torch.Size([1, 1, 1536]).
        size mismatch for pos_embed: copying a param with shape torch.Size([1, 1370, 384]) from checkpoint, the shape in current model is torch.Size([1, 1370, 1536]).
        size mismatch for mask_token: copying a param with shape torch.Size([1, 384]) from checkpoint, the shape in current model is torch.Size([1, 1536]).
        size mismatch for patch_embed.proj.weight: copying a param with shape torch.Size([384, 3, 14, 14]) from checkpoint, the shape in current model is torch.Size([1536, 3, 14, 14]).
        size mismatch for patch_embed.proj.bias: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([1536]).
        size mismatch for blocks.0.norm1.weight: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([1536]).
        size mismatch for blocks.0.norm1.bias: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([1536]).
        size mismatch for blocks.0.attn.qkv.weight: copying a param with shape torch.Size([1152, 384]) from checkpoint, the shape in current model is torch.Size([4608, 1536]).
        size mismatch for blocks.0.attn.qkv.bias: copying a param with shape torch.Size([1152]) from checkpoint, the shape in current model is torch.Size([4608]).
        size mismatch for blocks.0.attn.proj.weight: copying a param with shape torch.Size([384, 384]) from checkpoint, the shape in current model is torch.Size([1536, 1536]).
        size mismatch for blocks.0.attn.proj.bias: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([1536]).
        size mismatch for blocks.0.ls1.gamma: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([1536]).
        size mismatch for blocks.0.norm2.weight: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([1536]).
        size mismatch for blocks.0.norm2.bias: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([1536]).
        size mismatch for blocks.0.ls2.gamma: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([1536]).
        size mismatch for blocks.1.norm1.weight: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([1536]).
        size mismatch for blocks.1.norm1.bias: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([1536]).
        size mismatch for blocks.1.attn.qkv.weight: copying a param with shape torch.Size([1152, 384]) from checkpoint, the shape in current model is torch.Size([4608, 1536]).
        size mismatch for blocks.1.attn.qkv.bias: copying a param with shape torch.Size([1152]) from checkpoint, the shape in current model is torch.Size([4608]).
        size mismatch for blocks.1.attn.proj.weight: copying a param with shape torch.Size([384, 384]) from checkpoint, the shape in current model is torch.Size([1536, 1536]).
        size mismatch for blocks.1.attn.proj.bias: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([1536]).
        size mismatch for blocks.1.ls1.gamma: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([1536]).
        size mismatch for blocks.1.norm2.weight: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([1536]).
        size mismatch for blocks.1.norm2.bias: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([1536]).
        size mismatch for blocks.1.ls2.gamma: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([1536]).
        size mismatch for blocks.2.norm1.weight: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([1536]).
        size mismatch for blocks.2.norm1.bias: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([1536]).
        size mismatch for blocks.2.attn.qkv.weight: copying a param with shape torch.Size([1152, 384]) from checkpoint, the shape in current model is torch.Size([4608, 1536]).
        size mismatch for blocks.2.attn.qkv.bias: copying a param with shape torch.Size([1152]) from checkpoint, the shape in current model is torch.Size([4608]).
        size mismatch for blocks.2.attn.proj.weight: copying a param with shape torch.Size([384, 384]) from checkpoint, the shape in current model is torch.Size([1536, 1536]).
        size mismatch for blocks.2.attn.proj.bias: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([1536]).
        size mismatch for blocks.2.ls1.gamma: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([1536]).
        size mismatch for blocks.2.norm2.weight: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([1536]).
        size mismatch for blocks.2.norm2.bias: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([1536]).
        size mismatch for blocks.2.ls2.gamma: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([1536]).
        size mismatch for blocks.3.norm1.weight: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([1536]).
        size mismatch for blocks.3.norm1.bias: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([1536]).
        size mismatch for blocks.3.attn.qkv.weight: copying a param with shape torch.Size([1152, 384]) from checkpoint, the shape in current model is torch.Size([4608, 1536]).
        size mismatch for blocks.3.attn.qkv.bias: copying a param with shape torch.Size([1152]) from checkpoint, the shape in current model is torch.Size([4608]).
        size mismatch for blocks.3.attn.proj.weight: copying a param with shape torch.Size([384, 384]) from checkpoint, the shape in current model is torch.Size([1536, 1536]).
        size mismatch for blocks.3.attn.proj.bias: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([1536]).
        size mismatch for blocks.3.ls1.gamma: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([1536]).
        size mismatch for blocks.3.norm2.weight: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([1536]).
        size mismatch for blocks.3.norm2.bias: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([1536]).
        size mismatch for blocks.3.ls2.gamma: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([1536]).
        size mismatch for blocks.4.norm1.weight: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([1536]).
        size mismatch for blocks.4.norm1.bias: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([1536]).
        size mismatch for blocks.4.attn.qkv.weight: copying a param with shape torch.Size([1152, 384]) from checkpoint, the shape in current model is torch.Size([4608, 1536]).
        size mismatch for blocks.4.attn.qkv.bias: copying a param with shape torch.Size([1152]) from checkpoint, the shape in current model is torch.Size([4608]).
        size mismatch for blocks.4.attn.proj.weight: copying a param with shape torch.Size([384, 384]) from checkpoint, the shape in current model is torch.Size([1536, 1536]).
        size mismatch for blocks.4.attn.proj.bias: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([1536]).
        size mismatch for blocks.4.ls1.gamma: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([1536]).
        size mismatch for blocks.4.norm2.weight: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([1536]).
        size mismatch for blocks.4.norm2.bias: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([1536]).
        size mismatch for blocks.4.ls2.gamma: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([1536]).
        size mismatch for blocks.5.norm1.weight: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([1536]).
        size mismatch for blocks.5.norm1.bias: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([1536]).
        size mismatch for blocks.5.attn.qkv.weight: copying a param with shape torch.Size([1152, 384]) from checkpoint, the shape in current model is torch.Size([4608, 1536]).
        size mismatch for blocks.5.attn.qkv.bias: copying a param with shape torch.Size([1152]) from checkpoint, the shape in current model is torch.Size([4608]).
        size mismatch for blocks.5.attn.proj.weight: copying a param with shape torch.Size([384, 384]) from checkpoint, the shape in current model is torch.Size([1536, 1536]).
        size mismatch for blocks.5.attn.proj.bias: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([1536]).
        size mismatch for blocks.5.ls1.gamma: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([1536]).
        size mismatch for blocks.5.norm2.weight: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([1536]).
        size mismatch for blocks.5.norm2.bias: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([1536]).
        size mismatch for blocks.5.ls2.gamma: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([1536]).
        size mismatch for blocks.6.norm1.weight: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([1536]).
        size mismatch for blocks.6.norm1.bias: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([1536]).
        size mismatch for blocks.6.attn.qkv.weight: copying a param with shape torch.Size([1152, 384]) from checkpoint, the shape in current model is torch.Size([4608, 1536]).
        size mismatch for blocks.6.attn.qkv.bias: copying a param with shape torch.Size([1152]) from checkpoint, the shape in current model is torch.Size([4608]).
        size mismatch for blocks.6.attn.proj.weight: copying a param with shape torch.Size([384, 384]) from checkpoint, the shape in current model is torch.Size([1536, 1536]).
        size mismatch for blocks.6.attn.proj.bias: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([1536]).
        size mismatch for blocks.6.ls1.gamma: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([1536]).
        size mismatch for blocks.6.norm2.weight: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([1536]).
        size mismatch for blocks.6.norm2.bias: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([1536]).
        size mismatch for blocks.6.ls2.gamma: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([1536]).
        size mismatch for blocks.7.norm1.weight: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([1536]).
        size mismatch for blocks.7.norm1.bias: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([1536]).
        size mismatch for blocks.7.attn.qkv.weight: copying a param with shape torch.Size([1152, 384]) from checkpoint, the shape in current model is torch.Size([4608, 1536]).
        size mismatch for blocks.7.attn.qkv.bias: copying a param with shape torch.Size([1152]) from checkpoint, the shape in current model is torch.Size([4608]).
        size mismatch for blocks.7.attn.proj.weight: copying a param with shape torch.Size([384, 384]) from checkpoint, the shape in current model is torch.Size([1536, 1536]).
        size mismatch for blocks.7.attn.proj.bias: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([1536]).
        size mismatch for blocks.7.ls1.gamma: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([1536]).
        size mismatch for blocks.7.norm2.weight: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([1536]).
        size mismatch for blocks.7.norm2.bias: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([1536]).
        size mismatch for blocks.7.ls2.gamma: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([1536]).
        size mismatch for blocks.8.norm1.weight: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([1536]).
        size mismatch for blocks.8.norm1.bias: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([1536]).
        size mismatch for blocks.8.attn.qkv.weight: copying a param with shape torch.Size([1152, 384]) from checkpoint, the shape in current model is torch.Size([4608, 1536]).
        size mismatch for blocks.8.attn.qkv.bias: copying a param with shape torch.Size([1152]) from checkpoint, the shape in current model is torch.Size([4608]).
        size mismatch for blocks.8.attn.proj.weight: copying a param with shape torch.Size([384, 384]) from checkpoint, the shape in current model is torch.Size([1536, 1536]).
        size mismatch for blocks.8.attn.proj.bias: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([1536]).
        size mismatch for blocks.8.ls1.gamma: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([1536]).
        size mismatch for blocks.8.norm2.weight: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([1536]).
        size mismatch for blocks.8.norm2.bias: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([1536]).
        size mismatch for blocks.8.ls2.gamma: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([1536]).
        size mismatch for blocks.9.norm1.weight: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([1536]).
        size mismatch for blocks.9.norm1.bias: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([1536]).
        size mismatch for blocks.9.attn.qkv.weight: copying a param with shape torch.Size([1152, 384]) from checkpoint, the shape in current model is torch.Size([4608, 1536]).
        size mismatch for blocks.9.attn.qkv.bias: copying a param with shape torch.Size([1152]) from checkpoint, the shape in current model is torch.Size([4608]).
        size mismatch for blocks.9.attn.proj.weight: copying a param with shape torch.Size([384, 384]) from checkpoint, the shape in current model is torch.Size([1536, 1536]).
        size mismatch for blocks.9.attn.proj.bias: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([1536]).
        size mismatch for blocks.9.ls1.gamma: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([1536]).
        size mismatch for blocks.9.norm2.weight: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([1536]).
        size mismatch for blocks.9.norm2.bias: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([1536]).
        size mismatch for blocks.9.ls2.gamma: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([1536]).
        size mismatch for blocks.10.norm1.weight: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([1536]).
        size mismatch for blocks.10.norm1.bias: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([1536]).
        size mismatch for blocks.10.attn.qkv.weight: copying a param with shape torch.Size([1152, 384]) from checkpoint, the shape in current model is torch.Size([4608, 1536]).
        size mismatch for blocks.10.attn.qkv.bias: copying a param with shape torch.Size([1152]) from checkpoint, the shape in current model is torch.Size([4608]).
        size mismatch for blocks.10.attn.proj.weight: copying a param with shape torch.Size([384, 384]) from checkpoint, the shape in current model is torch.Size([1536, 1536]).
        size mismatch for blocks.10.attn.proj.bias: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([1536]).
        size mismatch for blocks.10.ls1.gamma: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([1536]).
        size mismatch for blocks.10.norm2.weight: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([1536]).
        size mismatch for blocks.10.norm2.bias: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([1536]).
        size mismatch for blocks.10.ls2.gamma: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([1536]).
        size mismatch for blocks.11.norm1.weight: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([1536]).
        size mismatch for blocks.11.norm1.bias: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([1536]).
        size mismatch for blocks.11.attn.qkv.weight: copying a param with shape torch.Size([1152, 384]) from checkpoint, the shape in current model is torch.Size([4608, 1536]).
        size mismatch for blocks.11.attn.qkv.bias: copying a param with shape torch.Size([1152]) from checkpoint, the shape in current model is torch.Size([4608]).
        size mismatch for blocks.11.attn.proj.weight: copying a param with shape torch.Size([384, 384]) from checkpoint, the shape in current model is torch.Size([1536, 1536]).
        size mismatch for blocks.11.attn.proj.bias: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([1536]).
        size mismatch for blocks.11.ls1.gamma: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([1536]).
        size mismatch for blocks.11.norm2.weight: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([1536]).
        size mismatch for blocks.11.norm2.bias: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([1536]).
        size mismatch for blocks.11.ls2.gamma: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([1536]).
        size mismatch for norm.weight: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([1536]).
        size mismatch for norm.bias: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([1536]).
